[pytest]
DJANGO_SETTINGS_MODULE = tests.settings
pythonpath = .
python_files = test_*.py
addopts = --reuse-db

markers =
    integration: marks tests that interact with real external services (e.g., Paystack). Use pytest -m integration to run these tests.