# Generated by Django 4.2.28 on 2026-02-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_infra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_inf_status_e35cf2_idx',
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at', 'idempotency_key', 'email'], name='payment_inf_status_316622_idx'),
        ),
    ]
