# Generated by Django 4.2.28 on 2026-03-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_infra', '0002_paymentwebhooklog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
    ]
